[build]
command = "bun run build"
publish = "dist"
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"

[blobs]
serve_options = { cors = { allowed_origins = ["*"] } }
public = true

[dev]
framework = "#custom"
command = "bun run dev"
targetPort = 5173
